version: "3.8"
services: 
  webbox1:
    build: 
      context: ./node_app
    environment: 
      - PORT=3001
      # internal docker port, nginx will need to loadbalance on this
    ports: 
      - 3010:3001
      # external port, for us to access, ex: via postman
  webbox2:
    build: 
      context: ./node_app
    environment: 
      - PORT=3002
    ports: 
      - 3020:3002
  nginx:
    restart: always
    build: 
      context: ./nginx_lb
    ports:
      - 3000:3000

      

# Links that helped
# https://ashwin9798.medium.com/nginx-with-docker-and-node-js-a-beginners-guide-434fe1216b6b
# https://auth0.com/blog/load-balancing-nodejs-applications-with-nginx-and-docker/
# https://stackoverflow.com/questions/56308574/how-can-i-use-nginx-for-load-balancer-simple-node-js-with-docker-compose